### ISSUE TITLE
address change documentation

### ISSUE THREAD

**Issue by blindguydiy** [OutdatedGuy/internet_connection_checker_plus#1]
Thanks for this one.  I need to change the default addresses, for some work places block the url's.  Do you have a better way to explain how to change the default addresses.  I am a blind guy and not sure if I am missing something that the screen reader is not reading.  But can not figure out how to change it.  Could you please give me a better example?  my email blindguydiy@gmail.com.  Thank you

**Comment by OutdatedGuy** [comment]
Thanks for using this package. You can change the default addresses by passing your own address to the `InternetConnectionCheckerPlus.createInstance` constructor.

Using the default constructor (i.e. `InternetConnectionCheckerPlus()`) will make use of the default addresses. Using the  createInstance constructor (i.e. `InternetConnectionCheckerPlus.createInstance()`) you can pass in your own custom addresses to the `addresses` parameter in the constructor which is a list of `AddressCheckOptions` class.

The `AddressCheckOptions` takes 1 positional argument and 2 optional named arguments.
The positional parameter is a `Uri` and the named parameters are:
1. `headers` which is a Map<String, String>
2. `timeout` which is the Duration value

The code will be as followed:
```dart
InternetConnectionCheckerPlus.createInstance(
  addresses: [
    AddressCheckOptions(
      Uri.parse('https://google.com'),
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
      },
      timeout: const Duration(seconds: 5),
    ),
    AddressCheckOptions(
      Uri.parse('https://youtube.com'),
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
      },
      timeout: const Duration(seconds: 2),
    ),
    AddressCheckOptions(
      Uri.parse('https://yahoo.com'),
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
      },
      timeout: const Duration(seconds: 15),
    ),
  ],
);
```
