### ISSUE TITLE
unable to use v2.0.0 with firebase storage plugin 

### ISSUE THREAD

**Issue by tksoh** [OutdatedGuy/internet_connection_checker_plus#10]
Hi, I am trying to use your latest plugin version 2.0.0 in my project that access firebase storage. However, pub get gave me some error:

> [internet_plus] flutter pub get
Resolving dependencies...
Because no versions of internet_connection_checker_plus match >2.0.0 <3.0.0 and internet_connection_checker_plus 2.0.0 depends on http ^1.0.0, internet_connection_checker_plus ^2.0.0 requires http ^1.0.0.
And because firebase_storage >=11.2.3 depends on firebase_storage_web ^3.6.3 which depends on http ^0.13.0, internet_connection_checker_plus ^2.0.0 is incompatible with firebase_storage >=11.2.3.
So, because internet_plus depends on both firebase_storage ^11.2.3 and internet_connection_checker_plus ^2.0.0, version solving failed.
exit code 1

Output of flutter doctor:

> $ puro flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.22621.1848], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.16)
[√] Android Studio (version 2021.2)
[√] VS Code, 64-bit edition (version 1.79.1)
[√] Connected device (4 available)
[√] Network resources
• No issues found!

Any thought on how to get around this problem?

Thanks.

**Comment by OutdatedGuy** [comment]
Yo @tksoh, this is an issue occurring due to `firebase_storage_web` plugin not updated latest version of `http` package.

There is already an issue raised in the [flutterfire repo](https://github.com/firebase/flutterfire/issues/11073).

Till then try using [1.0.1](https://pub.dev/packages/internet_connection_checker_plus/versions/1.0.1) version of this package.

**Comment by tksoh** [comment]
@OutdatedGuy Thanks for the pointer. I tried v1.0.1 and it's working for me. BTW, v2.0.0 seems a little faster on first internet check, but subsequent checks seem comparable. Is it true?

**Comment by OutdatedGuy** [comment]
@tksoh, I guess that's because in v2 is using `HEAD` request instead of a `GET` request. That might be reducing the payload which results in faster checks.

**Comment by OutdatedGuy** [comment]
@tksoh fixed in `v11.2.4` of [firebase_storage](https://pub.dev/packages/firebase_storage) plugin. You can now use `v2.0.0` of [internet_connection_checker_plus](https://pub.dev/packages/internet_connection_checker_plus).
