### ISSUE TITLE
SocketException with flutter 3.13.x

### ISSUE THREAD

**Issue by tksoh** [OutdatedGuy/internet_connection_checker_plus#12]
In my Android project using plugin v2.0.0, this error came up when debugging the app on VSCode (v1.18.1), with Flutter 3.13.0 & 3.13.1, when internet is offline.

> Exception has occurred.
SocketException (SocketException: Failed host lookup: 'icanhazip.com' (OS Error: The requested name is valid, but no data of the requested type was found.
, errno = 11004))

Output of flutter doctor:
> $ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.1, on Microsoft Windows [Version 10.0.22621.2134], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.16)
[√] Android Studio (version 2021.2)
[√] VS Code, 64-bit edition (version 1.81.1)
[√] Connected device (4 available)
[√] Network resources
• No issues found!

No issue with Flutter 3.10.5.

Please advice. Thanks.

**Comment by OutdatedGuy** [comment]
Is this the same as #11 ?

**Comment by tksoh** [comment]
@OutdatedGuy I'm not sure. #11 does not mention the flutter version used, and the exception type is different. In my case, the error is triggered by simply accessing `InternetConnection().hasInternetAccess` in the basic project created by 'flutter create'.

BTW, I just notice the error also happened when using plugin v1.0.0, maybe it has something to do on what the plugin is depending on.

One thing is that, the error is only caught if the "Uncaught Exception" is enabled in VSCode, else the app seems to run fine.

Another thing I don't understand is that wrapping the access to `InternetConnection().hasInternetAccess` in try-catch does nothing. Maybe there's some aspect of Dart I don't fully understand.

**Comment by OutdatedGuy** [comment]
@tksoh, Some issue with Flutter 3.13 I presume. Cuz after testing the issue on my side, the exception seems to be thrown in the `http` package.

But I have already wrapped that code in `try-catch` block.
https://github.com/OutdatedGuy/internet_connection_checker_plus/blob/f50bb13772af947deb065bd9e1adebe7231a7a16/lib/src/internet_connection.dart#L129-L141

So I downgraded the http package to `1.0.0` and even `0.13.6` but still the issue persists.

Can you confirm if the issue is not happening prior to flutter version `3.13`?

**Comment by OutdatedGuy** [comment]
Looks like the issue is with the latest Dart SDK that comes with Flutter 3.13: https://github.com/dart-lang/sdk/issues/53334

**Comment by tksoh** [comment]
Glad to know. Hopefully they can cut a new Dart soon on this.

**Comment by tksoh** [comment]
I just updated to Flutter 3.13.3, which is supposed to have fixed the issue with Dart 3.1.2, if I understand correctly, but I am still seeing this error unfortunately. Perhaps you can double check on your side?

$ flutter --version
Flutter 3.13.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2524052335 (6 days ago) • 2023-09-06 14:32:31 -0700
Engine • revision b8d35810e9
Tools • Dart 3.1.1 • DevTools 2.25.0

**Comment by tksoh** [comment]
Ah... I deleted my earlier reply. Looks like I mixed up on the Dart version in Flutter 3.13.3. My bad.

**Comment by tksoh** [comment]
Flutter 3.13.4 with Dart 3.1.2 fixed the issue.
