### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by ChristopheChanteur** [OutdatedGuy/internet_connection_checker_plus#2]
Hi Thank you for this GREAT package.
It works great on iOS simulator, unlike Connectivity_plus package which doesn't work properly on it.

Could you please update it to Dart 3, and maintain this package in the future please. 
I've been using your package for my projects for the past 6months and will intend to continue doing so.

Kind regards

Chris

**Comment by OutdatedGuy** [comment]
>  Hi Thank you for this GREAT package.

Thanks for using this package

> Could you please update it to Dart 3

I believe the package is already Dart 3 compatible and doesn't have anything to update

> maintain this package in the future please.

I'm planning to change the working of the package and upload a breaking change version (major version).
I'll try to maintain the package time to time. PRs are always welcomed tho.
