### ISSUE TITLE
[Feature Request] Stop listenning for internet status when app goes to background

### ISSUE THREAD

**Issue by orkun1675** [OutdatedGuy/internet_connection_checker_plus#27]
Apps are more likely to be killed by the OS if they keep using the network when they are in the background.

Using `AppLifecycleListener` can we stop the Timer that checks the network status when app is not in the foreground?

My app has no use for information about internet status when its not being actively used. I actually turn off all network services, such as Firebase document listeners, when app goes out of focus.

Thank you!

**Comment by OutdatedGuy** [comment]
Hi @orkun1675, this looks like a feature request as not many people are concerned with their app working in background.

I'm currently busy in some other work but if you can implement it, feel free to do it. PRs are always welcomed.

**Comment by Djsmk123** [comment]
@peer-f  are you still working on this??
