### ISSUE TITLE
InternetStatus and InternetConnection class not found

### ISSUE THREAD

**Issue by pishguy** [OutdatedGuy/internet_connection_checker_plus#28]
Why after adding this library into our project i can't use `InternetStatus` and `InternetConnection`?

source:

https://github.com/OutdatedGuy/internet_connection_checker_plus/blob/main/example/lib/pages/listen_to_stream.dart

**Comment by OutdatedGuy** [comment]
I think you have not installed the package properly, can you provide the snippet code for me to debug? Cuz I can make it work on every platform on my side.

**Comment by pishguy** [comment]
@OutdatedGuy 

You're mistaken. I installed the library and got an error. Then I realized that the documentation related to this library is outdated, and the names of classes and methods have changed, but they haven't been updated in the documentation.

**Comment by OutdatedGuy** [comment]
Can you provide your code where you are trying this package? Also the version of the package you are using and the output of `flutter doctor -v`.

**Comment by pishguy** [comment]
@OutdatedGuy 

After installing the library i tested only the codes of implemented source code inside sample

```
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.2.1 23C71 darwin-arm64, locale en-US)
    • Flutter version 3.16.5 on channel stable at /Users/mahdipishguy/Desktop/home/develop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (8 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
```

**Comment by OutdatedGuy** [comment]
Can you provide detailed steps from start till the error cuz I am unable to find any issues.

**Comment by AbdNz** [comment]
Try to use `InternetConnectionCheckerPlus` in place of `InternetConnection` and `InternetConnectionStatus` in place of `InternetStatus`

**Comment by OutdatedGuy** [comment]
@pishguy looks like you have installed a outdated version of this package. Try adding version `^2.0.0` or greater.

Closing as not an issue.

 Feel free to comment if you want to re-open this issue.
