### ISSUE TITLE
UI Lag Problems in v0.0.1

### ISSUE THREAD

**Issue by EmreSURK** [OutdatedGuy/internet_connection_checker_plus#54]
Hi,
Thanks for the package.

I am using the 0.0.1 version for a large and conflicted project. 

This package causes UI lags. For example: GestureDetector calls the OnTap function a couple of seconds delayed. Similar things happen when navigating, etc. Even Android OS's System UI stops responding frequently. 

It took me serious time to recognize the reason for the performance issue because I didn't suspect it from this package. 

Is this issue fixed in the newer version? Is it reported before? 

I tried to update the package to test myself but there is a lot of dependency conflict raised in my project, so I just wanted to ask you.

Thanks.

**Comment by OutdatedGuy** [comment]
v0.0.1 is not a stable release hence the issue might be occurring. Please update the package to at least `internet_connection_checker_plus: ^1.0.0` if not `^2.0.0`.

This issues hasn't been reported before as this package works in background hence not blocking the main UI thread.

**Comment by OutdatedGuy** [comment]
Closing this as stale. You can comment on this issue again to re-open it.
