### ISSUE TITLE
[Bug/Feature] Compilation issue with connectivity_plus, package update/change version is required

### ISSUE THREAD

**Issue by eulerchavez** [OutdatedGuy/internet_connection_checker_plus#55]
![Captura de pantalla 2024-08-16 a la(s) 8 33 10 p m](https://github.com/user-attachments/assets/7d085a9c-0337-4fe7-9053-58ee85adcb4c)

Issues related:

- https://github.com/fluttercommunity/plus_plugins/issues/3035 
- https://github.com/fluttercommunity/plus_plugins/issues/2965

**Comment by OutdatedGuy** [comment]
You need to update your flutter sdk and android studio to latest versions.

If that doesn't solve the issue, update `sourceCompatibility` and `targetCompatibility` to JavaVersion.VERSION_17

**Comment by dzakybrori** [comment]
> You need to update your flutter sdk and android studio to latest versions.
> 
> If that doesn't solve the issue, update `sourceCompatibility` and `targetCompatibility` to JavaVersion.VERSION_17

Is kotlinOptions.jvmTarget has to be upgrade to JavaVersion.VERSION_17 too?

**Comment by OutdatedGuy** [comment]
> Is kotlinOptions.jvmTarget has to be upgrade to JavaVersion.VERSION_17 too? @OutdatedGuy

@dzakybrori Most likely yes
