### ISSUE TITLE
[Bug] Error Execution failed for task ':connectivity_plus:compileDebugJavaWithJavac'

### ISSUE THREAD

**Issue by dzakybrori** [OutdatedGuy/internet_connection_checker_plus#62]
You need to update your flutter sdk and android studio to latest versions. If that doesn't solve the issue, update `sourceCompatibility` and `targetCompatibility` to JavaVersion.VERSION_17

_Originally posted by @OutdatedGuy in https://github.com/OutdatedGuy/internet_connection_checker_plus/issues/55#issuecomment-2294611199_
            
I already following the instruction to update` sourceCompatibility` and `targetCompatibility` to JavaVersion.VERSION_17 but still can't run the project.

I'm using this gradle:
``` distributionUrl=https\://services.gradle.org/distributions/gradle-8.3-all.zip ```

setting.gradle:
```
plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "8.1.0" apply false
    // START: FlutterFire Configuration
    id "com.google.gms.google-services" version "4.4.2" apply false
    // END: FlutterFire Configuration
    id "org.jetbrains.kotlin.android" version "1.8.22" apply false
}
```

```
* What went wrong:
Execution failed for task ':connectivity_plus:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':connectivity_plus:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: C:\Users\zack\AppData\Local\Android\Sdk\platforms\android-34\core-for-system-modules.jar.
         > Error while executing process C:\Program Files\Android\Android Studio\jbr\bin\jlink.exe with arguments {--module-path C:\Users\zack\.gradle\caches\transforms-3\e222b1aa9065c302d69ab0c2fea71aea\transformed\output\temp\jmod --add-modules java.base --output C:\Users\zack\.gradle\caches\transforms-3\e222b1aa9065c302d69ab0c2fea71aea\transformed\output\jdkImage --disable-plugin system-modules}

```

**Comment by OutdatedGuy** [comment]
@dzakybrori please post the contents of your `build.gradle` file

**Comment by kwamerex101** [comment]
facing the same issue, 
find below the contents of my build.gradle 

plugins {
    id "com.android.application"
    // START: FlutterFire Configuration
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
    // END: FlutterFire Configuration
    id "kotlin-android"
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id "dev.flutter.flutter-gradle-plugin"
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file("local.properties")
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader("UTF-8") { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty("flutter.versionCode")
if (flutterVersionCode == null) {
    flutterVersionCode = "1"
}

def flutterVersionName = localProperties.getProperty("flutter.versionName")
if (flutterVersionName == null) {
    flutterVersionName = "1.0"
}

android {
    namespace = "com.example.homekare"
    compileSdk = 34
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId = "com.example.homekare"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdk = 24
        targetSdk = 34
        versionCode = flutterVersionCode.toInteger()
        versionName = flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig = signingConfigs.debug
        }
    }
}

flutter {
    source = "../.."
}

**Comment by OutdatedGuy** [comment]
Check if you have fulfilled the [requirements](https://pub.dev/packages/connectivity_plus#requirements) for the `connectivity_plus` plugin.

![image](https://github.com/user-attachments/assets/dabb746d-145b-4a6f-8d42-b0993b9f69cc)

**Comment by dzakybrori** [comment]
@OutdatedGuy Which `build.gradle`? The one in the `app` folder or the on the project scope?

I found that this issue appear only in Android Studio Ladybug | 2024.2.1. I tried to run on the previous version of android studio it work fine. I didn't know how this issue appear. Do you think it's related to [this issue](https://github.com/flutter/flutter/issues/156111) ?

**Comment by OutdatedGuy** [comment]
@dzakybrori A few versions back on Android Studio (maybe Jellyfish idk), the default java version was switched from Java 8 to Java 17. And Java 8 will be removed completely from the future versions of Android studio.

I guess that is what causing the issue. You either need to fully migrate to Java 17 (preferable) or downgrade Android studio to still support Java 8.

**Comment by OutdatedGuy** [comment]
> @OutdatedGuy Which `build.gradle`? The one in the `app` folder or the on the project scope?

The app level gradle file.

**Comment by OutdatedGuy** [comment]
> I've been tried to use Java 17 but it seems effected any other packages. A lot of them still use Java 8. Even the flutter plugins create flutter project starter with Java 8. Do I really need to downgrade Android Studio or there is another solution?

Java 8 plugins should work on Java 17 without any major problems as far as I know. But the vice versa is not true.

**Comment by OutdatedGuy** [comment]
@kwamerex101 which version of Android Studio are you using? Also share the output of `java --version` and `flutter doctor -v`

**Comment by OutdatedGuy** [comment]
@dzakybrori found the issue. [Here is the work around](https://github.com/fluttercommunity/plus_plugins/issues/3299#issuecomment-2393426770).

Or, on Android Studio Lady Bug,
1. Open the android part of the flutter project
2. Tools -> AGP Upgrade Assistant
3. Select upgrade to version `8.7.0`
4. Click `Run Selected Steps`

This should solve the problem

**Comment by kwamerex101** [comment]
> @dzakybrori found the issue. [Here is the work around](https://github.com/fluttercommunity/plus_plugins/issues/3299#issuecomment-2393426770).
> 
> Or, on Android Studio Lady Bug,
> 
> 1. Open the android part of the flutter project
> 2. Tools -> AGP Upgrade Assistant
> 3. Select upgrade to version `8.7.0`
> 4. Click `Run Selected Steps`
> 
> This should solve the problem

This worked

**Comment by RuslanOrolbaev** [comment]
I just updated the Android Studio Lady Bug and faced this issue. 
In android/settings.gradle changing

from

plugins {
    id "com.android.application" version "**8.2.0**" apply false
}

to

plugins {
    id "com.android.application" version "**8.2.2**" apply false
}

solved the issue

**Comment by OutdatedGuy** [comment]
@dzakybrori closing as solution provided worked for other people. If you still have the issue, comment on here to reopen this thread.
